apiVersion: v1
kind: Service
metadata:
  name: {{ include "UserServiceChart.fullname" . }}
  labels:
    {{- include "UserServiceChart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9081
      protocol: TCP
      name: http
  selector:
    {{- include "UserServiceChart.selectorLabels" . | nindent 4 }}
